// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-gHC_IKCAGEz_a7983_CzGaeUQptn0U8',
    appId: '1:317442096502:web:968ac9275b287647050e57',
    messagingSenderId: '317442096502',
    projectId: 'flutter-firebase-app-e08e1',
    authDomain: 'flutter-firebase-app-e08e1.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-e08e1.appspot.com',
    measurementId: 'G-ZW89FKVMGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXlQsZlT0fomivF_OI6CcRB2_5-30eS6s',
    appId: '1:317442096502:android:e4fb0382f033feb1050e57',
    messagingSenderId: '317442096502',
    projectId: 'flutter-firebase-app-e08e1',
    storageBucket: 'flutter-firebase-app-e08e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3SZN735ax_nFxVTatT3JOR0a3U9FdKT4',
    appId: '1:317442096502:ios:5e47de258a2cf61f050e57',
    messagingSenderId: '317442096502',
    projectId: 'flutter-firebase-app-e08e1',
    storageBucket: 'flutter-firebase-app-e08e1.appspot.com',
    iosBundleId: 'com.example.fFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3SZN735ax_nFxVTatT3JOR0a3U9FdKT4',
    appId: '1:317442096502:ios:5e47de258a2cf61f050e57',
    messagingSenderId: '317442096502',
    projectId: 'flutter-firebase-app-e08e1',
    storageBucket: 'flutter-firebase-app-e08e1.appspot.com',
    iosBundleId: 'com.example.fFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-gHC_IKCAGEz_a7983_CzGaeUQptn0U8',
    appId: '1:317442096502:web:ea8a5a5075375d7e050e57',
    messagingSenderId: '317442096502',
    projectId: 'flutter-firebase-app-e08e1',
    authDomain: 'flutter-firebase-app-e08e1.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-e08e1.appspot.com',
    measurementId: 'G-DNN9DQL144',
  );
}
